- name: Collect SHA256 hashes from all Proxmox nodes
  hosts: ProxmoxServers
  become: yes
  gather_facts: yes
  
  vars:
    vm_id_min: 1000
    vm_id_max: 1100
    output_dir: "/tmp/vm-hashes"
  
  tasks:

    - name: Create output directory on Ansible server
      delegate_to: localhost
      run_once: yes
      become: no
      file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'

    - name: Collect VM hash data
      shell: |
        # Suppress errors from tools like zfs, lvs, etc
        exec 2>/dev/null

        # Filter VM IDs between configured range
        VM_LIST=$(qm list | awk "NR>1 && \$1 >= {{ vm_id_min }} && \$1 <= {{ vm_id_max }} {print \$1}")

        # If no VMs found output empty JSON and exit cleanly
        if [ -z "$VM_LIST" ]; then
          echo "[]"
          exit 0
        fi

        printf "["

        FIRST=1
        for VM_ID in $VM_LIST; do
          STATUS=$(qm status $VM_ID | awk '{print $2}')
          # Skip running VMs instead of failing
          if echo "$STATUS" | grep -qi "running"; then
            continue
          fi

          # Read VM config checksum
          CONFIG_HASH=$(sha256sum "/etc/pve/qemu-server/${VM_ID}.conf" | awk '{print $1}')

          # Print comma between VM objects
          if [ $FIRST -eq 0 ]; then
            printf ","
          fi
          FIRST=0

          printf '{"vm_id":%s,"status":"%s","config_hash":"%s","disks":[' "$VM_ID" "$STATUS" "$CONFIG_HASH"

          # Disk Discovery
          DISK_FIRST=1
          DISKS=""

          # Directory storage (can contain qcow2, raw, vmdk)
          if [ -d "/var/lib/vz/images/$VM_ID" ]; then
            DISKS="$DISKS $(find /var/lib/vz/images/$VM_ID -type f -name '*.qcow2' -o -name '*.raw' -o -name '*.vmdk')"
          fi

          # LVM/LVM-thin
          DISKS="$DISKS $(lvs --noheadings -o lv_path | grep "vm-${VM_ID}-")"

          # ZFS backing disks (skip snapshots)
          ZFS_LIST=$(zfs list -H -o name | grep "vm-${VM_ID}-" | grep -v '@')
          for ZNAME in $ZFS_LIST; do
            DISKS="$DISKS /dev/zvol/$ZNAME"
          done

          # Hash each discovered disk
          for DISK in $DISKS; do
            test -e "$DISK" || continue
            HASH=$(sha256sum "$DISK" | awk '{print $1}')
            if [ $DISK_FIRST -eq 0 ]; then
              printf ","
            fi
            DISK_FIRST=0
            printf '{"path":"%s","hash":"%s"}' "$DISK" "$HASH"
          done

          printf "]}"

        done
        printf "]"
      args:
        executable: /bin/bash
      register: vm_data_raw
      changed_when: false

    - name: Convert VM JSON
      set_fact:
        vm_data: "{{ vm_data_raw.stdout | from_json }}"

    - name: Save JSON to Ansible server
      delegate_to: localhost
      become: no
      copy:
        content: |
          {
            "node": "{{ ansible_hostname }}",
            "collection_date": "{{ ansible_date_time.iso8601 }}",
            "vms": {{ vm_data | to_nice_json }}
          }
        dest: "{{ output_dir }}/{{ ansible_hostname }}-hashes.json"
        mode: '0644'

# --------------------------------------------------------------------

- name: Create master manifest
  hosts: localhost
  gather_facts: yes
  vars:
    output_dir: "{{ playbook_dir }}/vm-hashes"

  tasks:

    - name: Find all hash files
      find:
        paths: "{{ output_dir }}"
        patterns: "*-hashes.json"
      register: hash_files

    - name: Initialize server list
      set_fact:
        all_servers: []

    - name: Load data from hash files
      when: hash_files.matched > 0
      set_fact:
        all_servers: "{{ all_servers + [lookup('file', item.path) | from_json] }}"
      loop: "{{ hash_files.files }}"
    
    - name: Skip manifest if nothing collected
      when: all_servers | length == 0
      debug:
        msg: "No offline VMs collected. Manifest not created."

    - name: Create master manifest
      when: all_servers | length > 0
      copy:
        content: |
          {
            "manifest_version": "1.0",
            "generated": "{{ ansible_date_time.iso8601 }}",
            "total_nodes": {{ all_servers | length }},
            "total_vms": {{ all_servers | map(attribute='vms') | map('length') | sum }},
            "nodes": {{ all_servers | to_nice_json }}
          }
        dest: "{{ output_dir }}/golden-images-manifest.json"
        mode: '0644'

    - name: Show summary
      debug:
        msg:
          - "Complete!"
          - "Nodes Scanned: {{ all_servers | length }}"
          - "Total VMs: {{ all_servers | map(attribute='vms') | map('length') | sum }}"
          - "Output Manifest: {{ output_dir }}/golden-images-manifest.json"
